//! Generic mapping from type-safe `FilterNode`<F> to `SeaORM` Conditions.
//!
//! This module provides the core logic for converting DTO-level filter expressions
//! into `SeaORM` conditions. Concrete modules only need to provide a mapping from
//! their DTO field enum to `SeaORM` Column types via the `FieldToColumn` trait.

use crate::secure::{Scoped, SecureSelect};
use bigdecimal::ToPrimitive;
use chrono::SecondsFormat;
use modkit_odata::filter::{
    FieldKind, FilterField, FilterNode, FilterOp, ODataValue, convert_expr_to_filter_node,
};
use modkit_odata::{CursorV1, Error as ODataError, ODataOrderBy, Page, PageInfo, SortDir};
use sea_orm::{
    Condition, EntityTrait, QueryFilter, QueryOrder, QuerySelect,
    sea_query::{Expr, Order},
};

use crate::secure::{DBRunner, DBRunnerInternal, SeaOrmRunner};

/// Error type for filter condition conversion failures.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum FilterConditionError {
    #[error("invalid composite operator: {op:?}")]
    InvalidCompositeOp { op: FilterOp },
    #[error("unsupported operator for NULL: {op:?}")]
    UnsupportedNullOp { op: FilterOp },
    #[error("logical operator {op:?} in binary context")]
    LogicalInBinaryContext { op: FilterOp },
    #[error("number value out of range")]
    NumberOutOfRange,
    #[error("invalid decimal value")]
    InvalidDecimal,
    #[error("IN list must not be empty")]
    EmptyInList,
    #[error("NULL values should be handled separately")]
    UnexpectedNull,
    #[error("expected string value, got {got}")]
    ExpectedString { got: &'static str },
}

/// Error type for cursor value encoding/decoding and extraction failures.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum CursorValueError {
    #[error("unknown orderby field: {name}")]
    UnknownOrderByField { name: String },
    #[error("cursor type mismatch for {kind:?}")]
    TypeMismatch { kind: FieldKind },
    #[error("invalid {kind:?} in cursor")]
    Parse {
        kind: FieldKind,
        #[source]
        source: Box<dyn std::error::Error + Send + Sync>,
    },
    #[error("invalid datetime format")]
    DateTimeFormat(#[source] Box<dyn std::error::Error + Send + Sync>),
}

/// Trait for mapping DTO filter fields to `SeaORM` columns.
///
/// This trait abstracts the mapping from a type-safe field enum (generated by
/// `#[derive(ODataFilterable)]`) to the corresponding `SeaORM` Column enum.
///
/// # Example
///
/// ```ignore
/// use modkit_db::odata::sea_orm_filter::FieldToColumn;
/// use crate::api::rest::dto::UserDtoFilterField;
/// use crate::testing::storage::entity::Column;
///
/// struct UserFieldMapper;
///
/// impl FieldToColumn<UserDtoFilterField> for UserFieldMapper {
///     type Column = Column;
///
///     fn map_field(field: UserDtoFilterField) -> Column {
///         match field {
///             UserDtoFilterField::Id => Column::Id,
///             UserDtoFilterField::Email => Column::Email,
///             UserDtoFilterField::CreatedAt => Column::CreatedAt,
///         }
///     }
/// }
/// ```
pub trait FieldToColumn<F: FilterField> {
    /// The `SeaORM` Column type for the entity
    type Column: Clone + sea_orm::Iden + sea_orm::ColumnTrait + sea_orm::IntoSimpleExpr + 'static;

    /// Map a DTO filter field to a `SeaORM` column
    fn map_field(field: F) -> Self::Column;
}

/// Extended trait for `OData` field mapping including cursor extraction.
///
/// This trait extends `FieldToColumn` with the ability to extract cursor values
/// from entity models, enabling type-safe pagination with ordering.
///
/// # Example
///
/// ```ignore
/// struct UserODataMapper;
///
/// impl FieldToColumn<UserDtoFilterField> for UserODataMapper {
///     type Column = Column;
///     fn map_field(field: UserDtoFilterField) -> Column { /* ... */ }
/// }
///
/// impl ODataFieldMapping<UserDtoFilterField> for UserODataMapper {
///     type Entity = Entity;
///     
///     fn extract_cursor_value(model: &Model, field: UserDtoFilterField) -> sea_orm::Value {
///         match field {
///             UserDtoFilterField::Id => sea_orm::Value::Uuid(Some(Box::new(model.id))),
///             UserDtoFilterField::Email => sea_orm::Value::String(Some(Box::new(model.email.clone()))),
///             UserDtoFilterField::CreatedAt => sea_orm::Value::ChronoDateTimeUtc(Some(Box::new(model.created_at))),
///         }
///     }
/// }
/// ```
pub trait ODataFieldMapping<F: FilterField>: FieldToColumn<F> {
    /// The `SeaORM` Entity type
    type Entity: EntityTrait;

    /// Extract a cursor value from a model for a specific field.
    ///
    /// This is used for cursor-based pagination to encode the values of
    /// ordering fields into the cursor.
    fn extract_cursor_value(
        model: &<Self::Entity as EntityTrait>::Model,
        field: F,
    ) -> sea_orm::Value;

    /// Extract cursor values for all fields in an order.
    ///
    /// This is a convenience method that can be overridden for optimization,
    /// but has a default implementation.
    ///
    /// # Errors
    /// Returns [`CursorValueError::UnknownOrderByField`] if an orderby field name is not recognized.
    fn extract_cursor_values(
        model: &<Self::Entity as EntityTrait>::Model,
        order: &ODataOrderBy,
    ) -> Result<Vec<(F, sea_orm::Value)>, CursorValueError> {
        let mut values = Vec::new();
        for order_key in &order.0 {
            let field = F::from_name(&order_key.field).ok_or_else(|| {
                CursorValueError::UnknownOrderByField {
                    name: order_key.field.clone(),
                }
            })?;
            let value = Self::extract_cursor_value(model, field);
            values.push((field, value));
        }
        Ok(values)
    }
}

/// Convert a `FilterNode`<F> to a `SeaORM` Condition using a `FieldToColumn` mapping.
///
/// This function provides generic traversal of the `FilterNode` AST and handles
/// all standard `OData` operations. Concrete modules only need to implement
/// `FieldToColumn` to map their DTO fields to database columns.
///
/// # Type Parameters
///
/// - `F`: The `FilterField` implementation (generated by `#[derive(ODataFilterable)]`)
/// - `M`: The `FieldToColumn` mapper that maps F to `SeaORM` columns
///
/// # Arguments
///
/// - `filter`: The type-safe filter node to convert
///
/// # Returns
///
/// A `SeaORM` Condition that can be applied to a query, or an error string if
/// the conversion fails.
///
/// # Example
///
/// ```ignore
/// let condition = filter_node_to_condition::<UserDtoFilterField, UserFieldMapper>(&filter)?;
/// let query = Entity::find().filter(condition);
/// ```
///
/// # Errors
/// Returns [`FilterConditionError`] if the filter contains unsupported operations or invalid values.
pub fn filter_node_to_condition<F, M>(
    filter: &FilterNode<F>,
) -> Result<Condition, FilterConditionError>
where
    F: FilterField,
    M: FieldToColumn<F>,
{
    match filter {
        FilterNode::Binary { field, op, value } => {
            // Map DTO field to database column
            let column = M::map_field(*field);
            build_binary_condition(column, *op, value)
        }
        FilterNode::InList { field, values } => {
            if values.is_empty() {
                return Err(FilterConditionError::EmptyInList);
            }
            let column = M::map_field(*field);
            let kind = field.kind();
            let sea_values: Vec<sea_orm::Value> = values
                .iter()
                .map(|v| odata_value_to_sea_value_for_kind(v, kind))
                .collect::<Result<_, _>>()?;
            Ok(Condition::all().add(Expr::col(column).is_in(sea_values)))
        }
        FilterNode::Composite { op, children } => {
            // Combine child conditions with AND or OR
            let base = match op {
                FilterOp::And => Condition::all(),
                FilterOp::Or => Condition::any(),
                _ => return Err(FilterConditionError::InvalidCompositeOp { op: *op }),
            };

            children.iter().try_fold(base, |acc, child| {
                let child_cond = filter_node_to_condition::<F, M>(child)?;
                Ok(acc.add(child_cond))
            })
        }
        FilterNode::Not(inner) => {
            // FIXED: Call .not() AFTER adding the inner condition
            let inner_cond = filter_node_to_condition::<F, M>(inner)?;
            Ok(Condition::all().add(inner_cond).not())
        }
    }
}

/// Build a binary condition (field op value) for `SeaORM`.
///
/// This handles all comparison and string function operations.
fn build_binary_condition<C>(
    column: C,
    op: FilterOp,
    value: &ODataValue,
) -> Result<Condition, FilterConditionError>
where
    C: sea_orm::Iden + sea_orm::ColumnTrait + sea_orm::IntoSimpleExpr + Clone + 'static,
{
    // Handle NULL specially *before* coercing to a sea_orm::Value so that
    // `field eq null` / `field ne null` are translated to IS NULL / IS NOT NULL
    // instead of bubbling up as `UnexpectedNull`.
    if matches!(value, ODataValue::Null) {
        return match op {
            FilterOp::Eq => Ok(Condition::all().add(Expr::col(column).is_null())),
            FilterOp::Ne => Ok(Condition::all().add(Expr::col(column).is_not_null())),
            _ => Err(FilterConditionError::UnsupportedNullOp { op }),
        };
    }

    // Convert ODataValue to sea_orm::Value
    let sea_value = odata_value_to_sea_value(value)?;

    // Build the expression based on the operator
    let expr = match op {
        FilterOp::Eq => Expr::col(column).eq(sea_value),
        FilterOp::Ne => Expr::col(column).ne(sea_value),
        FilterOp::Gt => Expr::col(column).gt(sea_value),
        FilterOp::Ge => Expr::col(column).gte(sea_value),
        FilterOp::Lt => Expr::col(column).lt(sea_value),
        FilterOp::Le => Expr::col(column).lte(sea_value),
        FilterOp::Contains => {
            let s = extract_string(value)?;
            Expr::col(column).like(format!("%{}%", escape_like(&s)))
        }
        FilterOp::StartsWith => {
            let s = extract_string(value)?;
            Expr::col(column).like(format!("{}%", escape_like(&s)))
        }
        FilterOp::EndsWith => {
            let s = extract_string(value)?;
            Expr::col(column).like(format!("%{}", escape_like(&s)))
        }
        FilterOp::In | FilterOp::And | FilterOp::Or => {
            return Err(FilterConditionError::LogicalInBinaryContext { op });
        }
    };

    Ok(Condition::all().add(expr))
}

/// Convert an `ODataValue` to a `sea_orm::Value`.
fn odata_value_to_sea_value(value: &ODataValue) -> Result<sea_orm::Value, FilterConditionError> {
    Ok(match value {
        ODataValue::String(s) => sea_orm::Value::String(Some(Box::new(s.clone()))),
        ODataValue::Number(n) => {
            // Try to convert to i64 first, then f64
            if let Some(i) = n.to_i64() {
                sea_orm::Value::BigInt(Some(i))
            } else if let Some(f) = n.to_f64() {
                sea_orm::Value::Double(Some(f))
            } else {
                return Err(FilterConditionError::NumberOutOfRange);
            }
        }
        ODataValue::Bool(b) => sea_orm::Value::Bool(Some(*b)),
        ODataValue::Uuid(u) => sea_orm::Value::Uuid(Some(Box::new(*u))),
        ODataValue::DateTime(dt) => sea_orm::Value::ChronoDateTimeUtc(Some(Box::new(*dt))),
        ODataValue::Date(d) => sea_orm::Value::ChronoDate(Some(Box::new(*d))),
        ODataValue::Time(t) => sea_orm::Value::ChronoTime(Some(Box::new(*t))),
        ODataValue::Null => {
            return Err(FilterConditionError::UnexpectedNull);
        }
    })
}

/// Convert an `ODataValue` to a `sea_orm::Value`, using the field's `FieldKind`
/// to coerce numeric values to the correct SQL type (especially Decimal).
fn odata_value_to_sea_value_for_kind(
    value: &ODataValue,
    kind: FieldKind,
) -> Result<sea_orm::Value, FilterConditionError> {
    match (kind, value) {
        (FieldKind::I64, ODataValue::Number(n)) => n
            .to_i64()
            .map(|i| sea_orm::Value::BigInt(Some(i)))
            .ok_or(FilterConditionError::NumberOutOfRange),
        (FieldKind::F64, ODataValue::Number(n)) => n
            .to_f64()
            .map(|f| sea_orm::Value::Double(Some(f)))
            .ok_or(FilterConditionError::NumberOutOfRange),
        (FieldKind::Decimal, ODataValue::Number(n)) => {
            let d = n
                .to_string()
                .parse::<rust_decimal::Decimal>()
                .map_err(|_| FilterConditionError::InvalidDecimal)?;
            Ok(sea_orm::Value::Decimal(Some(Box::new(d))))
        }
        _ => odata_value_to_sea_value(value),
    }
}

/// Returns a static string naming the variant of an [`ODataValue`].
fn odata_value_kind_name(value: &ODataValue) -> &'static str {
    match value {
        ODataValue::String(_) => "String",
        ODataValue::Number(_) => "Number",
        ODataValue::Bool(_) => "Bool",
        ODataValue::Uuid(_) => "Uuid",
        ODataValue::DateTime(_) => "DateTime",
        ODataValue::Date(_) => "Date",
        ODataValue::Time(_) => "Time",
        ODataValue::Null => "Null",
    }
}

/// Extract a string from an `ODataValue`.
fn extract_string(value: &ODataValue) -> Result<String, FilterConditionError> {
    match value {
        ODataValue::String(s) => Ok(s.clone()),
        _ => Err(FilterConditionError::ExpectedString {
            got: odata_value_kind_name(value),
        }),
    }
}

/// Escape special characters in LIKE patterns.
///
/// This escapes `%`, `_`, and `\` to prevent them from being interpreted
/// as wildcards in SQL LIKE patterns.
#[must_use]
pub fn escape_like(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '%' | '_' | '\\' => {
                out.push('\\');
                out.push(ch);
            }
            c => out.push(c),
        }
    }
    out
}

/// Encode a `sea_orm::Value` to a string for cursor storage.
///
/// This converts `SeaORM` values to strings that can be embedded in cursors.
///
/// # Errors
/// Returns [`CursorValueError`] if the value type doesn't match the expected kind or formatting fails.
pub fn encode_cursor_value(
    value: &sea_orm::Value,
    kind: FieldKind,
) -> Result<String, CursorValueError> {
    use sea_orm::Value as V;

    match (kind, value) {
        (FieldKind::String, V::String(Some(s))) => Ok(s.to_string()),
        (FieldKind::I64, V::BigInt(Some(i))) => Ok(i.to_string()),
        (FieldKind::F64, V::Double(Some(f))) => Ok(ryu::Buffer::new().format(*f).to_owned()),
        (FieldKind::Bool, V::Bool(Some(b))) => Ok(b.to_string()),
        (FieldKind::Uuid, V::Uuid(Some(u))) => Ok(u.to_string()),
        (FieldKind::DateTimeUtc, V::ChronoDateTimeUtc(Some(dt))) => {
            Ok(dt.to_rfc3339_opts(SecondsFormat::Nanos, true))
        }
        (FieldKind::DateTimeUtc, V::TimeDateTimeWithTimeZone(Some(dt))) => {
            let fmt = time::format_description::parse(
                "[year]-[month]-[day]T[hour]:[minute]:[second].[subsecond digits:9]Z",
            )
            .map_err(|e| CursorValueError::DateTimeFormat(Box::new(e)))?;
            dt.to_offset(time::UtcOffset::UTC)
                .format(&fmt)
                .map_err(|e| CursorValueError::DateTimeFormat(Box::new(e)))
        }
        (FieldKind::Date, V::ChronoDate(Some(d))) => Ok(d.to_string()),
        (FieldKind::Time, V::ChronoTime(Some(t))) => Ok(t.to_string()),
        (FieldKind::Decimal, V::Decimal(Some(d))) => Ok(d.to_string()),
        _ => Err(CursorValueError::TypeMismatch { kind }),
    }
}

/// Parse a cursor value from string based on field kind.
///
/// This is the inverse of `encode_cursor_value`, converting cursor strings
/// back to typed `SeaORM` values for comparison in queries.
///
/// # Errors
/// Returns [`CursorValueError`] if the string cannot be parsed as the expected type.
pub fn parse_cursor_value(kind: FieldKind, s: &str) -> Result<sea_orm::Value, CursorValueError> {
    use sea_orm::Value as V;

    let result = match kind {
        FieldKind::String => V::String(Some(Box::new(s.to_owned()))),
        FieldKind::I64 => {
            let i = s.parse::<i64>().map_err(|e| CursorValueError::Parse {
                kind,
                source: Box::new(e),
            })?;
            V::BigInt(Some(i))
        }
        FieldKind::F64 => {
            let f = s.parse::<f64>().map_err(|e| CursorValueError::Parse {
                kind,
                source: Box::new(e),
            })?;
            V::Double(Some(f))
        }
        FieldKind::Bool => {
            let b = s.parse::<bool>().map_err(|e| CursorValueError::Parse {
                kind,
                source: Box::new(e),
            })?;
            V::Bool(Some(b))
        }
        FieldKind::Uuid => {
            let u = s
                .parse::<uuid::Uuid>()
                .map_err(|e| CursorValueError::Parse {
                    kind,
                    source: Box::new(e),
                })?;
            V::Uuid(Some(Box::new(u)))
        }
        FieldKind::DateTimeUtc => {
            if let Ok(dt) =
                time::OffsetDateTime::parse(s, &time::format_description::well_known::Rfc3339)
            {
                V::TimeDateTimeWithTimeZone(Some(Box::new(dt)))
            } else {
                let dt = chrono::DateTime::parse_from_rfc3339(s)
                    .map_err(|e| CursorValueError::Parse {
                        kind,
                        source: Box::new(e),
                    })?
                    .with_timezone(&chrono::Utc);
                V::ChronoDateTimeUtc(Some(Box::new(dt)))
            }
        }
        FieldKind::Date => {
            let d = s
                .parse::<chrono::NaiveDate>()
                .map_err(|e| CursorValueError::Parse {
                    kind,
                    source: Box::new(e),
                })?;
            V::ChronoDate(Some(Box::new(d)))
        }
        FieldKind::Time => {
            let t = s
                .parse::<chrono::NaiveTime>()
                .map_err(|e| CursorValueError::Parse {
                    kind,
                    source: Box::new(e),
                })?;
            V::ChronoTime(Some(Box::new(t)))
        }
        FieldKind::Decimal => {
            let d = s
                .parse::<rust_decimal::Decimal>()
                .map_err(|e| CursorValueError::Parse {
                    kind,
                    source: Box::new(e),
                })?;
            V::Decimal(Some(Box::new(d)))
        }
    };

    Ok(result)
}

/// Pagination limit configuration
#[derive(Clone, Copy)]
pub struct LimitCfg {
    pub default: u64,
    pub max: u64,
}

/// Clamp the requested limit to configured bounds
fn clamp_limit(req: Option<u64>, cfg: LimitCfg) -> u64 {
    let mut l = req.unwrap_or(cfg.default);
    if l == 0 {
        l = 1;
    }
    if l > cfg.max {
        l = cfg.max;
    }
    l
}

/// Type-safe `OData` pagination with filters, ordering, and cursors.
///
/// This function provides complete cursor-based pagination using the type-safe
/// `FilterField` and `ODataFieldMapping` traits. It replaces the legacy FieldMap-based
/// pagination.
///
/// # Type Parameters
///
/// - `F`: `FilterField` implementation (generated by `#[derive(ODataFilterable)]`)
/// - `M`: `ODataFieldMapping` implementation that maps F to `SeaORM` columns and extracts cursor values
/// - `E`: `SeaORM` Entity type
/// - `D`: Domain/DTO type to map models to
/// - `Mapper`: Function to map `Entity::Model` to D
/// - `C`: Database connection type
///
/// # Arguments
///
/// - `select`: Base `SeaORM` select query (already security-scoped if needed)
/// - `conn`: Database connection
/// - `query`: `OData` query with filter, order, cursor, and limit
/// - `tiebreaker`: Default orderby field and direction for stable pagination
/// - `limit_cfg`: Default and maximum page sizes
/// - `model_to_domain`: Function to convert entity models to domain types
///
/// # Returns
///
/// A Page containing the results and pagination metadata (next/prev cursors)
///
/// # Example
///
/// ```ignore
/// let page = paginate_odata::<UserDtoFilterField, UserODataMapper, _, _, _, _>(
///     base_query,
///     db,
///     &odata_query,
///     ("id", SortDir::Desc),
///     LimitCfg { default: 25, max: 1000 },
///     |model| model.into(),
/// ).await?;
/// ```
///
/// # Errors
/// Returns `ODataError` if filter application, cursor validation, or database query fails.
pub async fn paginate_odata<F, M, E, D, Mapper, C>(
    select: SecureSelect<E, Scoped>,
    conn: &C,
    query: &modkit_odata::ODataQuery,
    tiebreaker: (&str, SortDir),
    limit_cfg: LimitCfg,
    model_to_domain: Mapper,
) -> Result<Page<D>, ODataError>
where
    F: FilterField,
    M: ODataFieldMapping<F, Entity = E>,
    E: EntityTrait,
    Mapper: Fn(E::Model) -> D,
    C: DBRunner,
{
    let limit = clamp_limit(query.limit, limit_cfg);
    let fetch = limit + 1;

    // Effective order derivation
    let effective_order = if let Some(cur) = &query.cursor {
        ODataOrderBy::from_signed_tokens(&cur.s).map_err(|_| ODataError::InvalidCursor)?
    } else {
        query
            .order
            .clone()
            .ensure_tiebreaker(tiebreaker.0, tiebreaker.1)
    };

    // Validate cursor consistency (filter hash only)
    if let Some(cur) = &query.cursor
        && let (Some(h), Some(cf)) = (query.filter_hash.as_deref(), cur.f.as_deref())
        && h != cf
    {
        return Err(ODataError::FilterMismatch);
    }

    let mut s = select.inner;

    // Apply filter using type-safe FilterNode
    if let Some(ast) = query.filter.as_deref() {
        let filter_node = convert_expr_to_filter_node::<F>(ast)
            .map_err(|e| ODataError::InvalidFilter(e.to_string()))?;

        s = s.filter(
            filter_node_to_condition::<F, M>(&filter_node)
                .map_err(|e| ODataError::InvalidFilter(e.to_string()))?,
        );
    }

    let is_backward = query.cursor.as_ref().is_some_and(|c| c.d == "bwd");

    // Apply cursor predicate
    if let Some(cursor) = &query.cursor {
        let cursor_cond = build_cursor_predicate::<F, M>(cursor, &effective_order)?;
        s = s.filter(cursor_cond);
    }

    // Apply ordering
    let query_order = if is_backward {
        effective_order.clone().reverse_directions()
    } else {
        effective_order.clone()
    };

    for order_key in &query_order.0 {
        let field = F::from_name(&order_key.field)
            .ok_or_else(|| ODataError::InvalidOrderByField(order_key.field.clone()))?;
        let column = M::map_field(field);
        let sea_order = match order_key.dir {
            SortDir::Asc => Order::Asc,
            SortDir::Desc => Order::Desc,
        };
        s = s.order_by(column, sea_order);
    }

    s = s.limit(fetch);

    #[allow(clippy::disallowed_methods)]
    let mut rows = match DBRunnerInternal::as_seaorm(conn) {
        SeaOrmRunner::Conn(db) => s.all(db).await,
        SeaOrmRunner::Tx(tx) => s.all(tx).await,
    }
    .map_err(|e| ODataError::Db(e.to_string()))?;

    let has_more = (rows.len() as u64) > limit;

    // Handle backward pagination reversal
    if is_backward {
        if has_more {
            rows.pop();
        }
        rows.reverse();
    } else if has_more {
        rows.truncate(usize::try_from(limit).unwrap_or(usize::MAX));
    }

    // Build cursors
    let next_cursor = if is_backward || has_more {
        build_cursor_from_rows::<E, F, M>(
            &rows,
            &effective_order,
            query.filter_hash.as_deref(),
            "fwd",
            true,
        )?
    } else {
        None
    };

    let prev_cursor = if is_backward {
        if has_more {
            build_cursor_from_rows::<E, F, M>(
                &rows,
                &effective_order,
                query.filter_hash.as_deref(),
                "bwd",
                false,
            )?
        } else {
            None
        }
    } else if query.cursor.is_some() {
        build_cursor_from_rows::<E, F, M>(
            &rows,
            &effective_order,
            query.filter_hash.as_deref(),
            "bwd",
            false,
        )?
    } else {
        None
    };

    let items = rows.into_iter().map(model_to_domain).collect();

    Ok(Page {
        items,
        page_info: PageInfo {
            next_cursor,
            prev_cursor,
            limit,
        },
    })
}

/// Build a cursor from rows, using either the first or last row
fn build_cursor_from_rows<E, F, M: ODataFieldMapping<F, Entity = E>>(
    rows: &[<E as EntityTrait>::Model],
    effective_order: &ODataOrderBy,
    filter_hash: Option<&str>,
    direction: &str,
    use_last: bool,
) -> Result<Option<String>, ODataError>
where
    F: FilterField,
    E: EntityTrait,
{
    let row = if use_last { rows.last() } else { rows.first() };

    row.map(|m| build_cursor_from_model::<F, M>(m, effective_order, filter_hash, direction))
        .transpose()
        .and_then(|opt| match opt {
            Some(c) => c.encode().map(Some).map_err(|_| ODataError::InvalidCursor),
            None => Ok(None),
        })
}

/// Build a cursor predicate for pagination
fn build_cursor_predicate<F, M>(
    cursor: &CursorV1,
    order: &ODataOrderBy,
) -> Result<Condition, ODataError>
where
    F: FilterField,
    M: ODataFieldMapping<F>,
{
    if cursor.k.len() != order.0.len() {
        return Err(ODataError::InvalidCursor);
    }

    // Parse all cursor values first
    let mut cursor_values: Vec<(F, M::Column, sea_orm::Value, SortDir)> = Vec::new();
    for (i, key_str) in cursor.k.iter().enumerate() {
        let order_key = &order.0[i];
        let field = F::from_name(&order_key.field)
            .ok_or(ODataError::InvalidOrderByField(order_key.field.clone()))?;
        let column = M::map_field(field);
        let kind = field.kind();
        let value = parse_cursor_value(kind, key_str).map_err(|_| ODataError::InvalidCursor)?;
        cursor_values.push((field, column, value, order_key.dir));
    }

    let is_backward = cursor.d == "bwd";
    let mut main_condition = Condition::any();

    for i in 0..cursor_values.len() {
        let mut prefix_condition = Condition::all();

        // Add equality conditions for all previous fields
        for (_field, column, value, _dir) in cursor_values.iter().take(i) {
            prefix_condition = prefix_condition.add(Expr::col(*column).eq(value.clone()));
        }

        // Add comparison for current field
        let (_field, column, value, dir) = &cursor_values[i];
        let comparison = if is_backward {
            // Backward: reverse the comparison
            match dir {
                SortDir::Asc => Expr::col(*column).lt(value.clone()),
                SortDir::Desc => Expr::col(*column).gt(value.clone()),
            }
        } else {
            // Forward: normal comparison
            match dir {
                SortDir::Asc => Expr::col(*column).gt(value.clone()),
                SortDir::Desc => Expr::col(*column).lt(value.clone()),
            }
        };

        prefix_condition = prefix_condition.add(comparison);
        main_condition = main_condition.add(prefix_condition);
    }

    Ok(main_condition)
}

/// Build a cursor from an entity model
fn build_cursor_from_model<F, M>(
    model: &<M::Entity as EntityTrait>::Model,
    order: &ODataOrderBy,
    filter_hash: Option<&str>,
    direction: &str,
) -> Result<CursorV1, ODataError>
where
    F: FilterField,
    M: ODataFieldMapping<F>,
{
    let field_values =
        M::extract_cursor_values(model, order).map_err(|_e| ODataError::InvalidCursor)?;

    let mut cursor_keys = Vec::new();
    for (field, value) in field_values {
        let kind = field.kind();
        let key_str = encode_cursor_value(&value, kind).map_err(|_| ODataError::InvalidCursor)?;
        cursor_keys.push(key_str);
    }

    // Determine primary sort direction from first order key
    let primary_dir = order.0.first().map_or(SortDir::Desc, |k| k.dir);

    Ok(CursorV1 {
        k: cursor_keys,
        o: primary_dir,
        s: order.to_signed_tokens(),
        f: filter_hash.map(str::to_owned),
        d: direction.to_owned(),
    })
}

#[cfg(test)]
#[cfg_attr(coverage_nightly, coverage(off))]
mod tests {
    use super::*;
    use bigdecimal::BigDecimal;
    use modkit_odata::filter::{FieldKind, FilterField, FilterNode, FilterOp, ODataValue};
    use std::error::Error as _;

    // Minimal SeaORM entity for testing FieldToColumn implementations.
    // Only used to satisfy the Column type bounds; no database is needed.
    mod test_entity {
        use sea_orm::entity::prelude::*;

        #[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
        #[sea_orm(table_name = "test")]
        pub struct Model {
            #[sea_orm(primary_key, auto_increment = false)]
            pub id: i64,
            pub name: String,
            pub count: i64,
        }

        #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
        pub enum Relation {}

        impl ActiveModelBehavior for ActiveModel {}
    }

    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    enum TestField {
        Name,
        Count,
    }

    impl FilterField for TestField {
        const FIELDS: &'static [Self] = &[Self::Name, Self::Count];

        fn name(&self) -> &'static str {
            match self {
                Self::Name => "name",
                Self::Count => "count",
            }
        }

        fn kind(&self) -> FieldKind {
            match self {
                Self::Name => FieldKind::String,
                Self::Count => FieldKind::I64,
            }
        }
    }

    struct TestMapper;

    impl FieldToColumn<TestField> for TestMapper {
        type Column = test_entity::Column;

        fn map_field(field: TestField) -> test_entity::Column {
            match field {
                TestField::Name => test_entity::Column::Name,
                TestField::Count => test_entity::Column::Count,
            }
        }
    }

    fn filter(field: TestField, op: FilterOp, value: ODataValue) -> FilterNode<TestField> {
        FilterNode::Binary { field, op, value }
    }

    fn composite(op: FilterOp, children: Vec<FilterNode<TestField>>) -> FilterNode<TestField> {
        FilterNode::Composite { op, children }
    }

    fn run(node: &FilterNode<TestField>) -> Result<Condition, FilterConditionError> {
        filter_node_to_condition::<TestField, TestMapper>(node)
    }

    // ── escape_like ──────────────────────────────────────────────────────────

    #[test]
    fn escape_like_no_special_chars() {
        assert_eq!(escape_like("hello world"), "hello world");
    }

    #[test]
    fn escape_like_percent() {
        assert_eq!(escape_like("50% off"), r"50\% off");
    }

    #[test]
    fn escape_like_underscore() {
        assert_eq!(escape_like("foo_bar"), r"foo\_bar");
    }

    #[test]
    fn escape_like_backslash() {
        assert_eq!(escape_like(r"C:\Users"), r"C:\\Users");
    }

    #[test]
    fn escape_like_multiple_special() {
        assert_eq!(escape_like("100%_done\\"), r"100\%\_done\\");
    }

    #[test]
    fn escape_like_empty() {
        assert_eq!(escape_like(""), "");
    }

    // ── FilterConditionError variants ────────────────────────────────────────

    #[test]
    fn filter_condition_error_invalid_composite_op_eq() {
        let node = composite(FilterOp::Eq, vec![]);
        let result = run(&node);
        assert!(matches!(
            result,
            Err(FilterConditionError::InvalidCompositeOp { op: FilterOp::Eq })
        ));
    }

    #[test]
    fn filter_condition_error_invalid_composite_op_gt() {
        let node = composite(FilterOp::Gt, vec![]);
        let result = run(&node);
        assert!(matches!(
            result,
            Err(FilterConditionError::InvalidCompositeOp { op: FilterOp::Gt })
        ));
    }

    #[test]
    fn filter_condition_eq_null_translates_to_is_null() {
        // `field eq null` must compile to `field IS NULL` and NOT bubble up
        // as `UnexpectedNull`. The earlier behaviour was a regression from
        // the typed-error rewrite (the NULL check was accidentally placed
        // after the value coercion).
        let node = filter(TestField::Name, FilterOp::Eq, ODataValue::Null);
        let result = run(&node).expect("eq null should produce IS NULL condition");
        let rendered = format!("{result:?}");
        assert!(rendered.contains("Is"), "expected an `IS NULL` condition");
        assert!(
            rendered.contains("Keyword(Null)"),
            "expected an `IS NULL` condition"
        );
    }

    #[test]
    fn filter_condition_ne_null_translates_to_is_not_null() {
        let node = filter(TestField::Name, FilterOp::Ne, ODataValue::Null);
        let result = run(&node).expect("ne null should produce IS NOT NULL condition");
        let rendered = format!("{result:?}");
        assert!(
            rendered.contains("IsNot"),
            "expected an `IS NOT NULL` condition"
        );
        assert!(
            rendered.contains("Keyword(Null)"),
            "expected an `IS NOT NULL` condition"
        );
    }

    #[test]
    fn filter_condition_unsupported_null_op() {
        // Only `eq` / `ne` are valid NULL operators; everything else must
        // fail with `UnsupportedNullOp`.
        let node = filter(TestField::Name, FilterOp::Gt, ODataValue::Null);
        let result = run(&node);
        assert!(matches!(
            result,
            Err(FilterConditionError::UnsupportedNullOp { op: FilterOp::Gt })
        ));
    }

    #[test]
    fn filter_condition_error_logical_in_binary_context_and() {
        let node = filter(
            TestField::Name,
            FilterOp::And,
            ODataValue::String("x".to_owned()),
        );
        let result = run(&node);
        assert!(matches!(
            result,
            Err(FilterConditionError::LogicalInBinaryContext { op: FilterOp::And })
        ));
    }

    #[test]
    fn filter_condition_error_logical_in_binary_context_or() {
        let node = filter(
            TestField::Name,
            FilterOp::Or,
            ODataValue::String("x".to_owned()),
        );
        let result = run(&node);
        assert!(matches!(
            result,
            Err(FilterConditionError::LogicalInBinaryContext { op: FilterOp::Or })
        ));
    }

    #[test]
    fn filter_condition_error_expected_string_on_contains_with_number() {
        let node = filter(
            TestField::Name,
            FilterOp::Contains,
            ODataValue::Number(BigDecimal::from(42)),
        );
        let result = run(&node);
        assert!(matches!(
            result,
            Err(FilterConditionError::ExpectedString { got: "Number" })
        ));
    }

    #[test]
    fn filter_condition_error_expected_string_on_startswith_with_bool() {
        let node = filter(
            TestField::Name,
            FilterOp::StartsWith,
            ODataValue::Bool(true),
        );
        let result = run(&node);
        assert!(matches!(
            result,
            Err(FilterConditionError::ExpectedString { got: "Bool" })
        ));
    }

    #[test]
    fn filter_condition_error_expected_string_on_endswith_with_bool() {
        let node = filter(TestField::Name, FilterOp::EndsWith, ODataValue::Bool(false));
        let result = run(&node);
        assert!(matches!(
            result,
            Err(FilterConditionError::ExpectedString { got: "Bool" })
        ));
    }

    // Happy-path binary conditions compile without error
    #[test]
    fn filter_condition_eq_string_succeeds() {
        let node = filter(
            TestField::Name,
            FilterOp::Eq,
            ODataValue::String("alice".to_owned()),
        );
        assert!(run(&node).is_ok());
    }

    #[test]
    fn filter_condition_contains_string_succeeds() {
        let node = filter(
            TestField::Name,
            FilterOp::Contains,
            ODataValue::String("ali".to_owned()),
        );
        assert!(run(&node).is_ok());
    }

    #[test]
    fn filter_condition_and_composite_succeeds() {
        let left = filter(
            TestField::Name,
            FilterOp::Eq,
            ODataValue::String("alice".to_owned()),
        );
        let right = filter(
            TestField::Count,
            FilterOp::Gt,
            ODataValue::Number(BigDecimal::from(0)),
        );
        let node = composite(FilterOp::And, vec![left, right]);
        assert!(run(&node).is_ok());
    }

    // ── FilterConditionError Display messages ─────────────────────────────────

    #[test]
    fn filter_condition_error_display_messages() {
        assert_eq!(
            FilterConditionError::InvalidCompositeOp { op: FilterOp::Gt }.to_string(),
            "invalid composite operator: Gt"
        );
        assert_eq!(
            FilterConditionError::UnsupportedNullOp { op: FilterOp::Gt }.to_string(),
            "unsupported operator for NULL: Gt"
        );
        assert_eq!(
            FilterConditionError::LogicalInBinaryContext { op: FilterOp::And }.to_string(),
            "logical operator And in binary context"
        );
        assert_eq!(
            FilterConditionError::NumberOutOfRange.to_string(),
            "number value out of range"
        );
        assert_eq!(
            FilterConditionError::UnexpectedNull.to_string(),
            "NULL values should be handled separately"
        );
        assert_eq!(
            FilterConditionError::ExpectedString { got: "Bool" }.to_string(),
            "expected string value, got Bool"
        );
    }

    // ── CursorValueError variants ─────────────────────────────────────────────

    // encode_cursor_value happy paths
    #[test]
    fn encode_cursor_value_string_ok() {
        let v = sea_orm::Value::String(Some(Box::new("hello".to_owned())));
        assert_eq!(encode_cursor_value(&v, FieldKind::String).unwrap(), "hello");
    }

    #[test]
    fn encode_cursor_value_i64_ok() {
        let v = sea_orm::Value::BigInt(Some(42));
        assert_eq!(encode_cursor_value(&v, FieldKind::I64).unwrap(), "42");
    }

    #[test]
    fn encode_cursor_value_bool_true_ok() {
        let v = sea_orm::Value::Bool(Some(true));
        assert_eq!(encode_cursor_value(&v, FieldKind::Bool).unwrap(), "true");
    }

    #[test]
    fn encode_cursor_value_bool_false_ok() {
        let v = sea_orm::Value::Bool(Some(false));
        assert_eq!(encode_cursor_value(&v, FieldKind::Bool).unwrap(), "false");
    }

    // encode_cursor_value TypeMismatch errors
    #[test]
    fn encode_cursor_value_type_mismatch_i64_field_string_value() {
        let v = sea_orm::Value::String(Some(Box::new("hello".to_owned())));
        let result = encode_cursor_value(&v, FieldKind::I64);
        assert!(
            matches!(
                result,
                Err(CursorValueError::TypeMismatch {
                    kind: FieldKind::I64
                })
            ),
            "expected TypeMismatch(I64), got {result:?}"
        );
    }

    #[test]
    fn encode_cursor_value_type_mismatch_string_field_int_value() {
        let v = sea_orm::Value::BigInt(Some(42));
        let result = encode_cursor_value(&v, FieldKind::String);
        assert!(matches!(
            result,
            Err(CursorValueError::TypeMismatch {
                kind: FieldKind::String
            })
        ));
    }

    #[test]
    fn encode_cursor_value_type_mismatch_uuid_field_bool_value() {
        let v = sea_orm::Value::Bool(Some(true));
        let result = encode_cursor_value(&v, FieldKind::Uuid);
        assert!(matches!(
            result,
            Err(CursorValueError::TypeMismatch {
                kind: FieldKind::Uuid
            })
        ));
    }

    // parse_cursor_value happy paths
    #[test]
    fn parse_cursor_value_string_ok() {
        let result = parse_cursor_value(FieldKind::String, "hello");
        assert!(matches!(result, Ok(sea_orm::Value::String(Some(_)))));
    }

    #[test]
    fn parse_cursor_value_i64_ok() {
        let result = parse_cursor_value(FieldKind::I64, "42");
        assert!(matches!(result, Ok(sea_orm::Value::BigInt(Some(42)))));
    }

    #[test]
    fn parse_cursor_value_i64_negative_ok() {
        let result = parse_cursor_value(FieldKind::I64, "-9999");
        assert!(matches!(result, Ok(sea_orm::Value::BigInt(Some(-9999)))));
    }

    #[test]
    fn parse_cursor_value_bool_true_ok() {
        let result = parse_cursor_value(FieldKind::Bool, "true");
        assert!(matches!(result, Ok(sea_orm::Value::Bool(Some(true)))));
    }

    #[test]
    fn parse_cursor_value_bool_false_ok() {
        let result = parse_cursor_value(FieldKind::Bool, "false");
        assert!(matches!(result, Ok(sea_orm::Value::Bool(Some(false)))));
    }

    // parse_cursor_value Parse errors
    #[test]
    fn parse_cursor_value_i64_parse_error() {
        let result = parse_cursor_value(FieldKind::I64, "not_a_number");
        assert!(
            matches!(
                result,
                Err(CursorValueError::Parse {
                    kind: FieldKind::I64,
                    ..
                })
            ),
            "expected Parse(I64), got {result:?}"
        );
        let err = result.unwrap_err();
        assert!(
            err.source().is_some(),
            "Parse error should expose its source"
        );
    }

    #[test]
    fn parse_cursor_value_f64_parse_error() {
        let result = parse_cursor_value(FieldKind::F64, "not_a_float");
        assert!(matches!(
            result,
            Err(CursorValueError::Parse {
                kind: FieldKind::F64,
                ..
            })
        ));
    }

    #[test]
    fn parse_cursor_value_bool_parse_error() {
        let result = parse_cursor_value(FieldKind::Bool, "maybe");
        assert!(matches!(
            result,
            Err(CursorValueError::Parse {
                kind: FieldKind::Bool,
                ..
            })
        ));
    }

    #[test]
    fn parse_cursor_value_uuid_parse_error() {
        let result = parse_cursor_value(FieldKind::Uuid, "not-a-uuid");
        assert!(matches!(
            result,
            Err(CursorValueError::Parse {
                kind: FieldKind::Uuid,
                ..
            })
        ));
    }

    #[test]
    fn parse_cursor_value_datetime_parse_error() {
        let result = parse_cursor_value(FieldKind::DateTimeUtc, "not-a-datetime");
        assert!(matches!(
            result,
            Err(CursorValueError::Parse {
                kind: FieldKind::DateTimeUtc,
                ..
            })
        ));
    }

    #[test]
    fn parse_cursor_value_date_parse_error() {
        let result = parse_cursor_value(FieldKind::Date, "not-a-date");
        assert!(matches!(
            result,
            Err(CursorValueError::Parse {
                kind: FieldKind::Date,
                ..
            })
        ));
    }

    #[test]
    fn parse_cursor_value_time_parse_error() {
        let result = parse_cursor_value(FieldKind::Time, "not-a-time");
        assert!(matches!(
            result,
            Err(CursorValueError::Parse {
                kind: FieldKind::Time,
                ..
            })
        ));
    }

    #[test]
    fn parse_cursor_value_decimal_parse_error() {
        let result = parse_cursor_value(FieldKind::Decimal, "not-a-decimal");
        assert!(matches!(
            result,
            Err(CursorValueError::Parse {
                kind: FieldKind::Decimal,
                ..
            })
        ));
    }

    // CursorValueError Display messages
    #[test]
    fn cursor_value_error_unknown_orderby_field_display() {
        let err = CursorValueError::UnknownOrderByField {
            name: "foo".to_owned(),
        };
        assert_eq!(err.to_string(), "unknown orderby field: foo");
    }

    #[test]
    fn cursor_value_error_type_mismatch_display() {
        let err = CursorValueError::TypeMismatch {
            kind: FieldKind::I64,
        };
        assert_eq!(err.to_string(), "cursor type mismatch for I64");
    }

    // parse_cursor_value / encode_cursor_value round-trip
    #[test]
    fn cursor_value_round_trip_string() {
        let encoded = encode_cursor_value(
            &sea_orm::Value::String(Some(Box::new("world".to_owned()))),
            FieldKind::String,
        )
        .unwrap();
        let decoded = parse_cursor_value(FieldKind::String, &encoded).unwrap();
        assert!(matches!(decoded, sea_orm::Value::String(Some(s)) if *s == "world"));
    }

    #[test]
    fn cursor_value_round_trip_i64() {
        let v = sea_orm::Value::BigInt(Some(-123));
        let encoded = encode_cursor_value(&v, FieldKind::I64).unwrap();
        let decoded = parse_cursor_value(FieldKind::I64, &encoded).unwrap();
        assert!(matches!(decoded, sea_orm::Value::BigInt(Some(-123))));
    }
}
